apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pma

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: asimabbasi1029/pma-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"