apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cloudforge-dev
  labels:
    app: backend
    environment: dev
    project: cloudforge

spec:
  type: ClusterIP
  selector:
    app: backend

  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  