apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: pma

spec:
  selector:
    app: backend

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500

  type: NodePort
  