apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: cloudforge-dev
  labels:
    app: worker
    environment: dev
    project: cloudforge

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker
        environment: dev

    spec:
      containers:
        - name: worker
          image: 125167623870.dkr.ecr.us-east-1.amazonaws.com/cloudforge-dev-backend:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
