name: Production CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check Node Version
        run: node --version

      - name: Check npm Version
        run: npm --version

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Check Docker Version
        run: docker --version

      - name: Build Frontend Docker Image
        run: docker build -t asimabbasi1029/pma-frontend:latest ./frontend

      - name: Build Backend Docker Image
        run: docker build -t asimabbasi1029/pma-backend:latest ./backend

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Frontend Docker Image
        run: docker push asimabbasi1029/pma-frontend:latest

      - name: Push Backend Docker Image
        run: docker push asimabbasi1029/pma-backend:latest
